giantswarm_weather:
    resource: "@GiantswarmWeatherBundle/Controller/"
    type:     annotation
    prefix:   /

tg_hello:
    resource: "@TgHelloProjectBundle/Controller"
    type:     annotation
    prefix:   /
